import { createMockCollection } from "@/shared/lib/mock/mockCollection";
import type { Article } from "@/services/article/types";

function cover(seed: string) {
  return `https://picsum.photos/seed/${seed}/960/540`;
}

const SEED: Article[] = [
  {
    id: "art-5-meo-giu-nha-gon-gang",
    title: "5 mẹo giữ nhà cửa gọn gàng mùa mưa",
    slug: "5-meo-giu-nha-cua-gon-gang-mua-mua",
    excerpt: "Mùa mưa khiến nhà cửa dễ ẩm thấp, bừa bộn hơn thường ngày. Đây là 5 thói quen đơn giản giúp không gian sống luôn ngăn nắp.",
    content:
      "# Vì sao nhà dễ bừa bộn hơn vào mùa mưa\n\nKhi trời mưa nhiều, đồ đạc ít được phơi nắng, quần áo và giày dép cũng dễ chất đống gần cửa ra vào.\n\n# 5 thói quen nên duy trì\n\n- Bố trí một kệ giày dép có mái che ngay lối vào\n- Dùng hộp đựng đồ có nắp để tránh ẩm mốc\n- Dọn dẹp góc phơi đồ trong nhà mỗi ngày\n- Đặt máy hút ẩm ở khu vực dễ ẩm như phòng ngủ, tủ quần áo\n- Sắp xếp lại tủ đồ theo mùa để không gian thoáng hơn\n\nDuy trì đều đặn, bạn sẽ thấy nhà cửa gọn gàng hơn hẳn dù thời tiết không thuận lợi.",
    coverImageUrl: cover("tidy-home-01"),
    categoryId: "cat-meo-trang-tri",
    categoryName: "Mẹo trang trí nhà cửa",
    tagIds: ["tag-tiet-kiem-dien-tich"],
    tagNames: ["Tiết kiệm diện tích"],
    relatedArticleIds: ["art-bo-tri-phong-khach-nho", "art-meo-mua-sam-noi-that"],
    author: "Minh Anh",
    featured: false,
    status: "published",
    publishedAt: "2026-08-16T09:20:00+07:00",
    updatedAt: "2026-08-16T09:20:00+07:00",
    views: 842,
    seoTitle: "5 mẹo giữ nhà cửa gọn gàng mùa mưa",
    seoDescription: "5 thói quen đơn giản giúp không gian sống luôn ngăn nắp, thoáng đãng trong mùa mưa.",
  },
  {
    id: "art-huong-dan-chon-nem",
    title: "Hướng dẫn chọn nệm phù hợp cho gia đình",
    slug: "huong-dan-chon-nem-phu-hop-cho-gia-dinh",
    excerpt: "Một chiếc nệm phù hợp ảnh hưởng trực tiếp đến chất lượng giấc ngủ cả gia đình. Đây là cách chọn đúng ngay từ đầu.",
    content:
      "Giấc ngủ ngon bắt đầu từ một chiếc nệm phù hợp với thể trạng và thói quen ngủ của từng người.\n\n# Những yếu tố cần cân nhắc\n\n- Độ cứng: người nằm nghiêng nên chọn nệm êm hơn để giảm áp lực lên vai và hông\n- Chất liệu: nệm foam giữ nhiệt, nệm lò xo thoáng khí hơn\n- Kích thước: đo kỹ không gian phòng ngủ trước khi chọn nệm cỡ lớn\n\nNếu gia đình có trẻ nhỏ hoặc người lớn tuổi, nên ưu tiên nệm có độ đàn hồi vừa phải, dễ nâng đỡ cột sống.",
    coverImageUrl: cover("mattress-02"),
    categoryId: "cat-meo-trang-tri",
    categoryName: "Mẹo trang trí nhà cửa",
    tagIds: ["tag-phong-ngu"],
    tagNames: ["Phòng ngủ"],
    relatedArticleIds: [],
    author: "Thu Hà",
    featured: true,
    status: "draft",
    updatedAt: "2026-08-14T17:10:00+07:00",
    views: 0,
    seoTitle: "Cách chọn nệm phù hợp cho cả gia đình",
    seoDescription: "Hướng dẫn chọn độ cứng, chất liệu và kích thước nệm phù hợp với từng thành viên trong nhà.",
  },
  {
    id: "art-bo-tri-phong-khach-nho",
    title: "Bí quyết bố trí phòng khách nhỏ trông rộng hơn",
    slug: "bi-quyet-bo-tri-phong-khach-nho-trong-rong-hon",
    excerpt: "Không cần đập thông tường, chỉ vài thay đổi nhỏ trong cách sắp xếp nội thất cũng giúp phòng khách thoáng đãng hơn hẳn.",
    content:
      "Phòng khách diện tích khiêm tốn vẫn có thể trông rộng rãi nếu biết chọn và sắp xếp nội thất đúng cách.\n\n# Chọn nội thất kích thước vừa phải\n\nGhế sofa nhỏ gọn, bàn trà thấp và kệ tivi treo tường giúp giải phóng diện tích sàn, tạo cảm giác thông thoáng.\n\n# Tận dụng ánh sáng và gương\n\nƯu tiên rèm mỏng để ánh sáng tự nhiên lan tỏa khắp phòng. Một tấm gương lớn đặt đối diện cửa sổ cũng giúp không gian trông sâu hơn.\n\n# Giữ màu sắc đồng bộ\n\nTường và nội thất cùng tông màu sáng giúp mắt không bị ngắt quãng, tạo cảm giác liền mạch, rộng rãi hơn.",
    coverImageUrl: cover("living-room-03"),
    categoryId: "cat-meo-trang-tri",
    categoryName: "Mẹo trang trí nhà cửa",
    tagIds: ["tag-phong-khach", "tag-tiet-kiem-dien-tich"],
    tagNames: ["Phòng khách", "Tiết kiệm diện tích"],
    relatedArticleIds: [],
    author: "Minh Anh",
    featured: true,
    status: "published",
    publishedAt: "2026-08-10T08:00:00+07:00",
    updatedAt: "2026-08-11T10:30:00+07:00",
    views: 1520,
    seoTitle: "Bố trí phòng khách nhỏ trông rộng hơn",
    seoDescription: "Mẹo chọn nội thất, ánh sáng và màu sắc giúp phòng khách nhỏ trông thoáng đãng và rộng rãi hơn.",
    canonicalUrl: "https://example-wcm-demo.vn/blog/bi-quyet-bo-tri-phong-khach-nho-trong-rong-hon",
  },
  {
    id: "art-xu-huong-noi-that-2026",
    title: "5 xu hướng nội thất được yêu thích năm 2026",
    slug: "5-xu-huong-noi-that-duoc-yeu-thich-nam-2026",
    excerpt: "Từ chất liệu tự nhiên đến gam màu đất, đây là những xu hướng nội thất đang được nhiều gia đình Việt lựa chọn.",
    content:
      "# Chất liệu tự nhiên lên ngôi\n\nGỗ sồi, mây, tre tiếp tục được ưa chuộng nhờ vẻ đẹp mộc mạc và độ bền cao.\n\n# Gam màu đất ấm áp\n\nCác tông màu nâu đất, cam đất, be thay thế dần cho các gam màu lạnh, mang lại cảm giác ấm cúng cho không gian sống.\n\n# Nội thất đa năng\n\nBàn ăn mở rộng, giường có ngăn kéo lưu trữ ngày càng phổ biến tại các căn hộ diện tích vừa và nhỏ.\n\n# Góc xanh trong nhà\n\nCây cảnh nhỏ đặt ở góc làm việc hoặc ban công tiếp tục là điểm nhấn được nhiều gia đình yêu thích.",
    coverImageUrl: cover("trend-04"),
    categoryId: "cat-xu-huong-noi-that",
    categoryName: "Xu hướng nội thất",
    tagIds: ["tag-noi-that-go", "tag-phong-cach-toi-gian"],
    tagNames: ["Nội thất gỗ", "Phong cách tối giản"],
    relatedArticleIds: [],
    author: "Quốc Bảo",
    featured: true,
    status: "published",
    publishedAt: "2026-08-02T09:00:00+07:00",
    updatedAt: "2026-08-03T14:20:00+07:00",
    views: 2310,
    seoTitle: "5 xu hướng nội thất 2026 đáng chú ý",
    seoDescription: "Điểm qua các xu hướng nội thất được yêu thích nhất năm 2026: chất liệu tự nhiên, màu đất, nội thất đa năng.",
  },
  {
    id: "art-cach-bao-quan-noi-that-go",
    title: "Cách bảo quản nội thất gỗ luôn bền đẹp",
    slug: "cach-bao-quan-noi-that-go-luon-ben-dep",
    excerpt: "Đồ gỗ nếu được chăm sóc đúng cách có thể sử dụng bền bỉ hàng chục năm mà vẫn giữ được vẻ đẹp tự nhiên.",
    content:
      "Gỗ tự nhiên rất nhạy cảm với độ ẩm và ánh nắng trực tiếp, vì vậy cần một vài lưu ý khi chăm sóc hằng ngày.\n\n# Vệ sinh đúng cách\n\n- Lau bụi bằng khăn mềm, khô thay vì khăn ướt\n- Tránh dùng hóa chất tẩy rửa mạnh trên bề mặt gỗ\n- Đánh bóng định kỳ 2-3 tháng một lần bằng dầu chuyên dụng\n\n# Vị trí đặt nội thất\n\nHạn chế đặt đồ gỗ nơi có ánh nắng chiếu trực tiếp hoặc gần nguồn nhiệt để tránh nứt, cong vênh theo thời gian.",
    coverImageUrl: cover("wood-care-05"),
    categoryId: "cat-cham-soc-bao-quan",
    categoryName: "Chăm sóc & bảo quản",
    tagIds: ["tag-bao-quan-do-go", "tag-noi-that-go"],
    tagNames: ["Bảo quản đồ gỗ", "Nội thất gỗ"],
    relatedArticleIds: ["art-xu-huong-noi-that-2026"],
    author: "Thu Hà",
    featured: false,
    status: "published",
    publishedAt: "2026-07-28T11:15:00+07:00",
    updatedAt: "2026-07-30T09:00:00+07:00",
    views: 967,
    seoTitle: "Cách bảo quản nội thất gỗ bền đẹp theo thời gian",
    seoDescription: "Hướng dẫn vệ sinh và bảo quản đồ nội thất gỗ tự nhiên đúng cách để giữ độ bền và thẩm mỹ lâu dài.",
  },
  {
    id: "art-khach-hang-chi-lan",
    title: "Không gian sống ấm cúng của chị Lan tại Long Biên",
    slug: "khong-gian-song-am-cung-cua-chi-lan-tai-long-bien",
    excerpt: "Cùng ghé thăm căn hộ 65m² được chị Lan cải tạo với nội thất gỗ tự nhiên, mang lại không gian ấm áp cho cả gia đình.",
    content:
      "Sau hơn một năm sử dụng, chị Lan chia sẻ về hành trình lựa chọn nội thất cho căn hộ nhỏ của gia đình mình.\n\n\"Mình ưu tiên đồ gỗ vì vừa bền vừa dễ phối với nhiều phong cách trang trí khác nhau,\" chị Lan cho biết.\n\nBộ bàn ăn mở rộng và kệ tivi đa năng là hai món đồ chị hài lòng nhất vì tối ưu được diện tích cho căn hộ nhỏ.",
    coverImageUrl: cover("customer-06"),
    categoryId: "cat-cau-chuyen-khach-hang",
    categoryName: "Câu chuyện khách hàng",
    tagIds: ["tag-noi-that-go", "tag-tiet-kiem-dien-tich"],
    tagNames: ["Nội thất gỗ", "Tiết kiệm diện tích"],
    relatedArticleIds: [],
    author: "Minh Anh",
    featured: false,
    status: "published",
    publishedAt: "2026-07-20T15:00:00+07:00",
    updatedAt: "2026-07-20T15:00:00+07:00",
    views: 611,
  },
  {
    id: "art-khai-truong-chi-nhanh-moi",
    title: "Khai trương showroom mới tại Quận 7",
    slug: "khai-truong-showroom-moi-tai-quan-7",
    excerpt: "Showroom thứ ba chính thức đi vào hoạt động, trưng bày đầy đủ các bộ sưu tập nội thất mới nhất trong năm nay.",
    content:
      "Showroom mới tại Quận 7 có diện tích trưng bày hơn 300m², giới thiệu đầy đủ các bộ sưu tập phòng khách, phòng ngủ và phòng ăn.\n\nSự kiện khai trương diễn ra vào cuối tuần này với nhiều ưu đãi dành cho khách hàng ghé thăm trực tiếp.",
    coverImageUrl: cover("news-07"),
    categoryId: "cat-tin-tuc-cong-ty",
    categoryName: "Tin tức công ty",
    tagIds: [],
    tagNames: [],
    relatedArticleIds: [],
    author: "Quốc Bảo",
    featured: false,
    status: "draft",
    updatedAt: "2026-08-13T08:30:00+07:00",
    views: 0,
  },
  {
    id: "art-phoi-mau-phong-ngu",
    title: "Cách phối màu phòng ngủ giúp ngủ ngon hơn",
    slug: "cach-phoi-mau-phong-ngu-giup-ngu-ngon-hon",
    excerpt: "Màu sắc trong phòng ngủ ảnh hưởng nhiều hơn bạn nghĩ đến chất lượng giấc ngủ. Đây là những gam màu nên cân nhắc.",
    content:
      "# Gam màu trung tính giúp thư giãn\n\nBe, xám nhạt và trắng ngà là những lựa chọn an toàn giúp không gian ngủ dịu mắt, dễ chịu.\n\n# Điểm nhấn từ màu đất\n\nMột mảng tường màu nâu đất hoặc xanh rêu nhạt phía đầu giường tạo chiều sâu mà không gây rối mắt.\n\n# Tránh màu quá sáng hoặc tương phản mạnh\n\nMàu sắc quá chói dễ khiến não bộ khó thư giãn trước khi ngủ, nên hạn chế ở khu vực phòng ngủ.",
    coverImageUrl: cover("bedroom-08"),
    categoryId: "cat-meo-trang-tri",
    categoryName: "Mẹo trang trí nhà cửa",
    tagIds: ["tag-phong-ngu", "tag-phong-cach-toi-gian"],
    tagNames: ["Phòng ngủ", "Phong cách tối giản"],
    relatedArticleIds: ["art-huong-dan-chon-nem"],
    author: "Thu Hà",
    featured: false,
    status: "published",
    publishedAt: "2026-07-15T09:40:00+07:00",
    updatedAt: "2026-07-16T13:00:00+07:00",
    views: 1043,
    seoTitle: "Phối màu phòng ngủ giúp ngủ ngon hơn",
    seoDescription: "Gợi ý các gam màu phù hợp cho phòng ngủ để tạo không gian thư giãn, dễ đi vào giấc ngủ hơn.",
  },
  {
    id: "art-meo-mua-sam-noi-that",
    title: "5 lưu ý trước khi mua nội thất online",
    slug: "5-luu-y-truoc-khi-mua-noi-that-online",
    excerpt: "Mua nội thất qua mạng tiện lợi nhưng cũng dễ gặp rủi ro nếu không kiểm tra kỹ. Đây là những điều nên làm trước khi đặt hàng.",
    content:
      "Mua sắm nội thất trực tuyến giúp tiết kiệm thời gian, nhưng cần lưu ý một số điểm để tránh mua nhầm sản phẩm không phù hợp.\n\n- Đo đạc kỹ không gian trước khi chọn kích thước\n- Đọc kỹ mô tả chất liệu, không chỉ nhìn hình ảnh\n- Kiểm tra chính sách đổi trả trước khi thanh toán\n- Ưu tiên cửa hàng có đánh giá và hình ảnh thực tế từ khách hàng\n- Hỏi rõ thời gian giao hàng, đặc biệt với đồ nội thất kích thước lớn",
    coverImageUrl: cover("shopping-09"),
    categoryId: "cat-meo-trang-tri",
    categoryName: "Mẹo trang trí nhà cửa",
    tagIds: ["tag-mua-sam-thong-minh"],
    tagNames: ["Mua sắm thông minh"],
    relatedArticleIds: [],
    author: "Minh Anh",
    featured: false,
    status: "published",
    publishedAt: "2026-07-05T10:00:00+07:00",
    updatedAt: "2026-07-05T10:00:00+07:00",
    views: 1287,
    seoTitle: "5 lưu ý khi mua nội thất online",
    seoDescription: "Những điều cần kiểm tra trước khi đặt mua nội thất qua mạng để tránh rủi ro không đáng có.",
  },
  {
    id: "art-thiet-ke-goc-lam-viec",
    title: "Thiết kế góc làm việc tại nhà gọn gàng, hiệu quả",
    slug: "thiet-ke-goc-lam-viec-tai-nha-gon-gang-hieu-qua",
    excerpt: "Không cần một căn phòng riêng, một góc nhỏ được bố trí hợp lý cũng đủ để tạo không gian làm việc tập trung tại nhà.",
    content:
      "Làm việc tại nhà ngày càng phổ biến, và một góc làm việc gọn gàng giúp tăng đáng kể sự tập trung.\n\n# Chọn vị trí có ánh sáng tự nhiên\n\nĐặt bàn làm việc gần cửa sổ giúp giảm mỏi mắt và tiết kiệm điện năng vào ban ngày.\n\n# Ưu tiên nội thất gọn nhẹ\n\nBàn làm việc gấp gọn hoặc kệ treo tường là lựa chọn phù hợp cho không gian nhỏ.",
    coverImageUrl: cover("workspace-10"),
    categoryId: "cat-xu-huong-noi-that",
    categoryName: "Xu hướng nội thất",
    tagIds: ["tag-tiet-kiem-dien-tich"],
    tagNames: ["Tiết kiệm diện tích"],
    relatedArticleIds: [],
    author: "Quốc Bảo",
    featured: false,
    status: "draft",
    updatedAt: "2026-08-09T16:45:00+07:00",
    views: 0,
  },
];

export const articleCollection = createMockCollection(SEED, {
  entityName: "Article",
  keywordFields: ["title", "slug", "author"],
});
