import { createMockCollection } from "@/shared/lib/mock/mockCollection";
import type { Product } from "@/services/product/types";

function coverImage(name: string): string {
  return `https://placehold.co/600x400?text=${encodeURIComponent(name)}`;
}

const SEED: Product[] = [
  {
    id: "prod-sofa-lumo",
    name: "Sofa góc bọc vải nỉ Lumo",
    slug: "sofa-goc-boc-vai-ni-lumo",
    shortDescription: "Sofa góc bọc vải nỉ mềm, khung gỗ chắc chắn, phù hợp phòng khách vừa và nhỏ.",
    description:
      "Sofa góc Lumo có thiết kế hiện đại, đệm mút D40 êm ái và lớp vải nỉ chống bám bẩn dễ vệ sinh. Khung gỗ tự nhiên xử lý chống mối mọt, chân gỗ chắc chắn nâng đỡ tốt cho không gian tiếp khách gia đình.",
    categoryId: "cat-living-room",
    categoryName: "Nội thất phòng khách",
    featured: true,
    status: "published",
    seoTitle: "Sofa góc bọc vải nỉ Lumo - Nội thất phòng khách",
    seoDescription: "Sofa góc Lumo bọc vải nỉ êm ái, khung gỗ bền chắc, thiết kế hiện đại cho phòng khách.",
    coverImageUrl: coverImage("Sofa goc Lumo"),
    updatedAt: "2026-08-15T09:20:00+07:00",
  },
  {
    id: "prod-ban-an-solace",
    name: "Bàn ăn gỗ sồi tự nhiên 6 chỗ Solace",
    slug: "ban-an-go-soi-tu-nhien-6-cho-solace",
    shortDescription: "Bàn ăn gỗ sồi tự nhiên, mặt bàn dày 3cm, đủ chỗ cho gia đình 6 người.",
    description:
      "Bàn ăn Solace được làm từ gỗ sồi tự nhiên nguyên khối, giữ nguyên vân gỗ mộc mạc và độ bền cao theo thời gian. Kích thước rộng rãi phù hợp cho bữa cơm gia đình hoặc tiếp khách.",
    categoryId: "cat-living-room",
    categoryName: "Nội thất phòng khách",
    featured: false,
    status: "published",
    seoTitle: "Bàn ăn gỗ sồi 6 chỗ Solace",
    seoDescription: "Bàn ăn gỗ sồi tự nhiên Solace, mặt bàn dày dặn, đủ chỗ cho gia đình 6 người.",
    coverImageUrl: coverImage("Ban an Solace"),
    updatedAt: "2026-08-14T10:05:00+07:00",
  },
  {
    id: "prod-ban-tra-nordic",
    name: "Bàn trà mặt kính chân sắt Nordic",
    slug: "ban-tra-mat-kinh-chan-sat-nordic",
    shortDescription: "Bàn trà phong cách Bắc Âu, mặt kính cường lực, chân sắt sơn tĩnh điện.",
    description:
      "Thiết kế tối giản theo phong cách Bắc Âu, mặt kính cường lực dày 8mm chịu lực tốt, chân sắt sơn tĩnh điện chống gỉ. Phù hợp phối cùng sofa hiện đại.",
    categoryId: "cat-living-room",
    categoryName: "Nội thất phòng khách",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Ban tra Nordic"),
    updatedAt: "2026-08-10T15:40:00+07:00",
  },
  {
    id: "prod-giuong-serene",
    name: "Giường ngủ gỗ công nghiệp MDF Serene",
    slug: "giuong-ngu-go-cong-nghiep-mdf-serene",
    shortDescription: "Giường ngủ khung gỗ MDF phủ melamine chống ẩm, thiết kế đầu giường bọc nệm.",
    description:
      "Giường Serene sử dụng gỗ công nghiệp MDF lõi xanh chống ẩm, phủ melamine chống trầy xước. Đầu giường bọc nệm êm ái, phù hợp phòng ngủ hiện đại.",
    categoryId: "cat-bedroom",
    categoryName: "Nội thất phòng ngủ",
    featured: true,
    status: "published",
    seoTitle: "Giường ngủ MDF Serene - Đầu giường bọc nệm",
    seoDescription: "Giường ngủ Serene khung gỗ công nghiệp chống ẩm, đầu giường bọc nệm êm ái.",
    coverImageUrl: coverImage("Giuong Serene"),
    updatedAt: "2026-08-13T08:30:00+07:00",
  },
  {
    id: "prod-tu-quan-ao-harmony",
    name: "Tủ quần áo 4 cánh Harmony",
    slug: "tu-quan-ao-4-canh-harmony",
    shortDescription: "Tủ quần áo 4 cánh, nhiều ngăn kéo, tối ưu không gian lưu trữ phòng ngủ.",
    description:
      "Tủ Harmony có 4 cánh cửa cùng hệ ngăn kéo và thanh treo linh hoạt, giúp sắp xếp quần áo gọn gàng. Bản lề giảm chấn êm ái, bền bỉ theo thời gian sử dụng.",
    categoryId: "cat-bedroom",
    categoryName: "Nội thất phòng ngủ",
    featured: false,
    status: "draft",
    coverImageUrl: coverImage("Tu quan ao Harmony"),
    updatedAt: "2026-08-09T13:50:00+07:00",
  },
  {
    id: "prod-ke-dau-giuong-aurora",
    name: "Kệ đầu giường mini Aurora",
    slug: "ke-dau-giuong-mini-aurora",
    shortDescription: "Kệ đầu giường nhỏ gọn, 2 ngăn kéo tiện lợi, phù hợp phòng ngủ diện tích nhỏ.",
    description:
      "Kệ đầu giường Aurora thiết kế nhỏ gọn với 2 ngăn kéo trơn êm, mặt trên đủ rộng để đặt đèn ngủ hoặc sách. Chất liệu gỗ công nghiệp phủ melamine dễ lau chùi.",
    categoryId: "cat-bedroom",
    categoryName: "Nội thất phòng ngủ",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Ke dau giuong Aurora"),
    updatedAt: "2026-08-07T11:15:00+07:00",
  },
  {
    id: "prod-ghe-ergoflex",
    name: "Ghế làm việc công thái học ErgoFlex Pro",
    slug: "ghe-lam-viec-cong-thai-hoc-ergoflex-pro",
    shortDescription: "Ghế công thái học tựa lưng lưới thoáng khí, hỗ trợ cột sống khi ngồi lâu.",
    description:
      "ErgoFlex Pro có lưng ghế lưới thoáng khí, tựa đầu và tay vịn điều chỉnh được, cùng đệm ngồi mút lạnh giảm áp lực. Phù hợp cho người làm việc tại nhà nhiều giờ mỗi ngày.",
    categoryId: "cat-home-office",
    categoryName: "Bàn ghế văn phòng tại nhà",
    featured: true,
    status: "published",
    seoTitle: "Ghế công thái học ErgoFlex Pro cho dân văn phòng",
    seoDescription: "Ghế ErgoFlex Pro hỗ trợ cột sống, lưng lưới thoáng khí, tay vịn điều chỉnh linh hoạt.",
    coverImageUrl: coverImage("Ghe ErgoFlex Pro"),
    updatedAt: "2026-08-16T07:45:00+07:00",
  },
  {
    id: "prod-ban-lam-viec-smartdesk",
    name: "Bàn làm việc gấp gọn SmartDesk",
    slug: "ban-lam-viec-gap-gon-smartdesk",
    shortDescription: "Bàn làm việc gấp gọn tiết kiệm diện tích, lắp đặt nhanh trong 5 phút.",
    description:
      "SmartDesk gấp gọn dễ dàng khi không sử dụng, khung thép chịu lực tốt và mặt bàn phủ chống nước. Lựa chọn phù hợp cho phòng làm việc nhỏ hoặc căn hộ studio.",
    categoryId: "cat-home-office",
    categoryName: "Bàn ghế văn phòng tại nhà",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Ban SmartDesk"),
    updatedAt: "2026-08-06T09:00:00+07:00",
  },
  {
    id: "prod-bo-noi-kitchen-master",
    name: "Bộ nồi inox 5 món Kitchen Master",
    slug: "bo-noi-inox-5-mon-kitchen-master",
    shortDescription: "Bộ 5 nồi inox 3 đáy, dùng được cho bếp từ, đáy dẫn nhiệt nhanh và đều.",
    description:
      "Bộ nồi Kitchen Master gồm 5 kích cỡ khác nhau, chất liệu inox 304 an toàn thực phẩm, đáy 3 lớp dẫn nhiệt nhanh và đều. Tương thích mọi loại bếp kể cả bếp từ.",
    categoryId: "cat-kitchen",
    categoryName: "Đồ gia dụng nhà bếp",
    featured: true,
    status: "published",
    seoTitle: "Bộ nồi inox 5 món Kitchen Master - Dùng cho mọi loại bếp",
    seoDescription: "Bộ nồi inox 304 Kitchen Master, đáy 3 lớp dẫn nhiệt nhanh, dùng được cho bếp từ.",
    coverImageUrl: coverImage("Bo noi Kitchen Master"),
    updatedAt: "2026-08-12T14:10:00+07:00",
  },
  {
    id: "prod-may-xay-blendy",
    name: "Máy xay sinh tố mini Blendy",
    slug: "may-xay-sinh-to-mini-blendy",
    shortDescription: "Máy xay sinh tố mini công suất 300W, cối xay bằng nhựa Tritan an toàn.",
    description:
      "Blendy nhỏ gọn với công suất 300W đủ mạnh để xay hoa quả, đá bào. Cối xay chất liệu Tritan không chứa BPA, dễ dàng tháo rời để vệ sinh.",
    categoryId: "cat-kitchen",
    categoryName: "Đồ gia dụng nhà bếp",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("May xay Blendy"),
    updatedAt: "2026-08-04T16:30:00+07:00",
  },
  {
    id: "prod-den-ban-lumina",
    name: "Đèn bàn LED chống cận Lumina",
    slug: "den-ban-led-chong-can-lumina",
    shortDescription: "Đèn bàn LED chống cận, 5 mức độ sáng, cổng sạc USB tích hợp.",
    description:
      "Lumina cung cấp ánh sáng dịu mắt với 5 mức độ sáng và 3 tông màu điều chỉnh được, phù hợp cho học tập và làm việc. Tích hợp cổng sạc USB tiện lợi ngay trên thân đèn.",
    categoryId: "cat-lighting",
    categoryName: "Đèn trang trí & chiếu sáng",
    featured: true,
    status: "published",
    seoTitle: "Đèn bàn LED chống cận Lumina",
    seoDescription: "Đèn bàn Lumina chống cận, 5 mức sáng, tích hợp cổng sạc USB tiện lợi.",
    coverImageUrl: coverImage("Den ban Lumina"),
    updatedAt: "2026-08-16T06:20:00+07:00",
  },
  {
    id: "prod-den-chum-stella",
    name: "Đèn chùm pha lê mini Stella",
    slug: "den-chum-pha-le-mini-stella",
    shortDescription: "Đèn chùm pha lê mini, ánh sáng lung linh, phù hợp phòng khách nhỏ.",
    description:
      "Stella mang đến vẻ sang trọng cho không gian với các tinh thể pha lê phản chiếu ánh sáng lung linh. Kích thước mini phù hợp trần nhà thấp hoặc phòng khách diện tích vừa.",
    categoryId: "cat-lighting",
    categoryName: "Đèn trang trí & chiếu sáng",
    featured: false,
    status: "draft",
    coverImageUrl: coverImage("Den chum Stella"),
    updatedAt: "2026-08-03T10:50:00+07:00",
  },
  {
    id: "prod-den-san-nordik",
    name: "Đèn sàn đứng phong cách Bắc Âu Nordik",
    slug: "den-san-dung-phong-cach-bac-au-nordik",
    shortDescription: "Đèn sàn đứng tối giản, chân gỗ tự nhiên, chao vải mềm mại.",
    description:
      "Nordik theo phong cách Bắc Âu tối giản với chân đế gỗ tự nhiên vững chãi và chao đèn vải mềm mại tỏa ánh sáng ấm áp, phù hợp góc đọc sách hoặc phòng khách.",
    categoryId: "cat-lighting",
    categoryName: "Đèn trang trí & chiếu sáng",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Den san Nordik"),
    updatedAt: "2026-08-02T09:10:00+07:00",
  },
  {
    id: "prod-guong-luna",
    name: "Gương trang trí treo tường hình tròn Luna",
    slug: "guong-trang-tri-treo-tuong-hinh-tron-luna",
    shortDescription: "Gương tròn viền kim loại mảnh, làm điểm nhấn trang trí cho tường nhà.",
    description:
      "Luna là gương trang trí hình tròn với viền kim loại mảnh tinh tế, giúp không gian trông rộng và sáng hơn. Dễ dàng treo ở phòng khách, hành lang hoặc phòng ngủ.",
    categoryId: "cat-decor-accessories",
    categoryName: "Phụ kiện trang trí nhà",
    featured: true,
    status: "published",
    seoTitle: "Gương trang trí tròn Luna cho phòng khách",
    seoDescription: "Gương tròn Luna viền kim loại mảnh, điểm nhấn trang trí tinh tế cho mọi không gian.",
    coverImageUrl: coverImage("Guong Luna"),
    updatedAt: "2026-08-11T12:00:00+07:00",
  },
  {
    id: "prod-binh-hoa-terra",
    name: "Bình hoa gốm sứ trang trí Terra",
    slug: "binh-hoa-gom-su-trang-tri-terra",
    shortDescription: "Bình hoa gốm sứ thủ công, họa tiết mộc mạc, phù hợp trang trí bàn trà.",
    description:
      "Terra được làm thủ công từ gốm sứ với họa tiết mộc mạc mang hơi hướng tự nhiên. Kích thước vừa phải, phù hợp cắm hoa khô hoặc hoa tươi trang trí bàn trà, kệ sách.",
    categoryId: "cat-decor-accessories",
    categoryName: "Phụ kiện trang trí nhà",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Binh hoa Terra"),
    updatedAt: "2026-08-01T08:40:00+07:00",
  },
  {
    id: "prod-tham-boho",
    name: "Thảm trải sàn phòng khách họa tiết Boho",
    slug: "tham-trai-san-phong-khach-hoa-tiet-boho",
    shortDescription: "Thảm trải sàn họa tiết Boho, chất liệu sợi mềm, chống trượt.",
    description:
      "Thảm Boho mang họa tiết hình học phong cách bohemian, dệt từ sợi mềm mại an toàn cho trẻ nhỏ. Lớp lót đế chống trượt giữ thảm cố định trên mọi bề mặt sàn.",
    categoryId: "cat-rugs-curtains",
    categoryName: "Thảm & rèm cửa",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Tham Boho"),
    updatedAt: "2026-07-31T15:00:00+07:00",
  },
  {
    id: "prod-rem-cua",
    name: "Rèm cửa sổ vải lanh 2 lớp",
    slug: "rem-cua-so-vai-lanh-2-lop",
    shortDescription: "Rèm cửa sổ vải lanh 2 lớp, cản sáng vừa phải, giữ không gian thoáng đãng.",
    description:
      "Rèm vải lanh 2 lớp gồm lớp voan mỏng và lớp vải dày, dễ dàng phối hợp để điều chỉnh độ sáng theo nhu cầu. Chất liệu thoáng mát, phù hợp khí hậu nhiệt đới.",
    categoryId: "cat-rugs-curtains",
    categoryName: "Thảm & rèm cửa",
    featured: false,
    status: "draft",
    coverImageUrl: coverImage("Rem cua vai lanh"),
    updatedAt: "2026-07-29T10:20:00+07:00",
  },
  {
    id: "prod-ke-sach",
    name: "Kệ sách treo tường 5 tầng",
    slug: "ke-sach-treo-tuong-5-tang",
    shortDescription: "Kệ sách treo tường 5 tầng, tiết kiệm diện tích sàn, lắp đặt đơn giản.",
    description:
      "Kệ sách 5 tầng treo trực tiếp lên tường giúp tiết kiệm diện tích sàn, phù hợp trưng bày sách và đồ trang trí nhỏ. Đi kèm phụ kiện lắp đặt đầy đủ, dễ dàng tự lắp tại nhà.",
    categoryId: "cat-storage",
    categoryName: "Kệ & tủ lưu trữ",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Ke sach treo tuong"),
    updatedAt: "2026-08-05T13:15:00+07:00",
  },
  {
    id: "prod-tu-tai-lieu",
    name: "Tủ tài liệu văn phòng 3 ngăn",
    slug: "tu-tai-lieu-van-phong-3-ngan",
    shortDescription: "Tủ tài liệu 3 ngăn kéo, khóa an toàn, phù hợp góc làm việc tại nhà.",
    description:
      "Tủ tài liệu 3 ngăn kéo có khóa an toàn cho từng ngăn, chất liệu gỗ công nghiệp chống ẩm. Thiết kế nhỏ gọn phù hợp đặt cạnh bàn làm việc tại nhà hoặc văn phòng nhỏ.",
    categoryId: "cat-storage",
    categoryName: "Kệ & tủ lưu trữ",
    featured: false,
    status: "draft",
    coverImageUrl: coverImage("Tu tai lieu van phong"),
    updatedAt: "2026-07-27T09:30:00+07:00",
  },
  {
    id: "prod-chau-cay-evergreen",
    name: "Chậu cây giả trang trí sân vườn Evergreen",
    slug: "chau-cay-gia-trang-tri-san-vuon-evergreen",
    shortDescription: "Chậu cây giả bền màu, không cần chăm sóc, phù hợp trang trí sân vườn hoặc ban công.",
    description:
      "Evergreen là cây giả với lá bền màu, chịu được nắng mưa ngoài trời mà không cần chăm sóc. Chậu nhựa giả đá đi kèm giúp hoàn thiện góc trang trí sân vườn hoặc ban công.",
    categoryId: "cat-garden",
    categoryName: "Trang trí sân vườn",
    featured: false,
    status: "published",
    coverImageUrl: coverImage("Chau cay Evergreen"),
    updatedAt: "2026-07-25T14:45:00+07:00",
  },
];

export const productCollection = createMockCollection(SEED, {
  entityName: "Product",
  keywordFields: ["name", "slug", "shortDescription"],
});
